#!/bin/bash

set -a # auto-export all env vars

CFG_NAMESPACE="$1"
shift

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
CONFIG_DIR="${CONFIG_DIR:-$XDG_CONFIG_HOME/$CFG_NAMESPACE}"
CONFIG="${CONFIG:-$CONFIG_DIR/config.sh}"

if [ -r "$CONFIG" ]; then
  source "$CONFIG"
fi

CACHE_DIR="${CACHE_DIR:-$XDG_CACHE_HOME/$CFG_NAMESPACE}"

exec "$@"
